### ISSUE TITLE
Unsafe assumptions about location of ssh key

### ISSUE THREAD

**Issue by raneq** [coopdevs/devenv#16]
https://github.com/coopdevs/devenv/blob/d424f7507c7ef327a774bf737d5c789fbedc0322/create-container.sh#L104

User may want to use another ssh key, create a new one, or have their own key with another crypto algorithm, like elliptic curve, so that id_rsa.pub may not be found.

Should this be interactive, read the option as a parameter, as an environment variable?

In case of environment variable, this is useful to use a default if the var is unset or "":

```
# Assign the default path to ssh_path or leave it intact if it is already set.
${ssh_path:="$HOME/.ssh/id_rsa.pub"}
```
[More on this syntax](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_02)

It should be also prompted to user at some time to make them aware of the possibility.

**Comment by enricostano** [comment]
What about adding this stuff in some config file. `.devenv` is at project level, maybe some `/etc/devenv` or something like that at system/user level would be nice.

**Comment by raneq** [comment]
Yes, taking into account that devenv gets installed system wide available for many projects, I think it makes sense to place the config at /etc . Some tools look also into equivalent directories inside user home, but it may be not worth it.
I can do that, there may be other system user preferences to extract.
