### ISSUE TITLE
No start logs with debian stretch

### ISSUE THREAD

**Issue by raneq** [coopdevs/devenv#20]
Script says "Please check log file /var/log/lxc/$NAME.log" a couple of times, but no call to lxc refers to this logfile. The manpages for `lxc-create` say: 
```
-o, --logfile=FILE
    Output to an alternate log FILE. The default is no log.
```

So default is no log. But maybe it's set somewhere else? In my system I can't find `/var/log/lxc`.

I propose to modify calls to `lxc-create` and `lxc-start` to add this option. We should see if it is worth it to log also `lxc-attach` calls.

**Comment by enricostano** [comment]
`/var/log/lxc` is created on Ubuntu and Arch. Cannot reproduce.

**Comment by raneq** [comment]
> `/var/log/lxc` is created on Ubuntu and Arch. Cannot reproduce.

In Debian Buster i still have the issue, but you choose the systems you support!

**Comment by enricostano** [comment]
@raneq if you want to add full support for Debian Buster, please feel free to create a PR. Thanks!
