### ISSUE TITLE
Create sudo repeated on lines 230 and 264

### ISSUE THREAD

**Issue by mperezv** [coopdevs/devenv#30]
https://github.com/coopdevs/devenv/blob/9be082d8baaa6cb595a06ef1b230d02baab9eb09/create-container.sh#L230
https://github.com/coopdevs/devenv/blob/9be082d8baaa6cb595a06ef1b230d02baab9eb09/create-container.sh#L264

**Comment by mperezv** [comment]
Solved here --> https://github.com/coopdevs/devenv/pull/31#

**Comment by enricostano** [comment]
> Solved here

@mperezv you can use this when an already merged PR solves an open issue. In this case you should add "Fix #30" in the PR description.

I reopen this issue since the PR is still open.

**Comment by mperezv** [comment]
Ok! Thanks Enrico! :smile:

**Comment by mperezv** [comment]
Fixed in #31
